import { db } from "./db";
import { chat, extractJson } from "./llm";

// "Chat with your money": natural-language question -> a single read-only SELECT
// generated by the local LLM -> validated -> executed -> narrated.
// The validator is the security boundary; the LLM never touches the DB directly.

const SCHEMA = `
TABLE transactions(
  id TEXT, account_id TEXT, date TEXT (YYYY-MM-DD), name TEXT, merchant TEXT,
  amount REAL (positive = money OUT/spent, negative = money IN/received),
  currency TEXT, pending INTEGER, plaid_category TEXT, category TEXT,
  entity TEXT ('personal' | 'business'), reviewed INTEGER)
TABLE accounts(
  id TEXT, name TEXT, type TEXT, subtype TEXT, current_balance REAL, currency TEXT)
Join: transactions.account_id = accounts.id
`;

const SQL_SYSTEM = `You translate a personal-finance question into ONE SQLite SELECT query.
Schema:${SCHEMA}
Sign + category conventions (critical — get these right):
- amount > 0 means money LEFT the account (spending/outflow).
- amount < 0 means money CAME IN (income/refund/transfer-in).
- "Spending" = SUM(amount) WHERE amount > 0, and EXCLUDE category IN
  ('Transfer:Internal','Transfer:Brokerage','CreditCardPayment') — those are money
  moving between your own accounts, not spending. Return spending as a positive number.
- "Income" = SUM(-amount) WHERE category = 'Income'. Do NOT treat every inflow as
  income; transfers in are not income. Return income as a positive number.
- "Net worth" = SUM over accounts of current_balance, subtracting credit/loan balances.
Output rules:
- Output ONLY JSON: {"sql": "<single SELECT>", "note": "<one-line what it computes>"}.
- SELECT only. No INSERT/UPDATE/DELETE/PRAGMA/ATTACH/semicolons.
- Prefer returning already-signed, human-friendly positive totals (use -amount or
  ABS where the convention above says so) so the number reads naturally.
- Use date() comparisons for time windows (e.g. date >= date('now','-30 days')).
- Always include a sensible LIMIT (<= 200).`;

const ANSWER_SYSTEM = `You are a concise personal-finance assistant. Given the user's
question and the SQL result rows (JSON), answer in 1-3 sentences with concrete
numbers. Format money as $X,XXX.XX. The query already applies sign conventions, so
report totals as given (a positive income/spending total is correct — never report
income or spending as negative). No preamble, no caveats unless the data is empty.`;

// --- Validator: the security gate ---
const ALLOWED_TABLES = ["transactions", "accounts"];
// CTE names defined by WITH are allowed as FROM/JOIN targets too.
const BANNED = /\b(insert|update|delete|drop|alter|create|replace|attach|detach|pragma|vacuum|reindex|trigger)\b/i;

export function validateSql(sql: string): { ok: boolean; reason?: string; safe?: string } {
  const s = sql.trim().replace(/;+\s*$/, "");
  if (s.includes(";")) return { ok: false, reason: "multiple statements" };
  // Read-only statements start with SELECT or WITH (a CTE that resolves to SELECT).
  if (!/^(select|with)\b/i.test(s)) return { ok: false, reason: "not a read-only query" };
  if (BANNED.test(s)) return { ok: false, reason: "banned keyword" };
  // Collect CTE names from `WITH name AS (...)`, `, name AS (...)` so they don't
  // trip the table allowlist (they're derived, not real tables).
  const cteNames = new Set(
    [...s.matchAll(/(?:\bwith\s+|,\s*)([a-z_][a-z0-9_]*)\s+as\s*\(/gi)].map((m) => m[1].toLowerCase())
  );
  const refs = [...s.matchAll(/\b(?:from|join)\s+([a-z_][a-z0-9_]*)/gi)].map((m) => m[1].toLowerCase());
  for (const t of refs) {
    if (!ALLOWED_TABLES.includes(t) && !cteNames.has(t)) {
      return { ok: false, reason: `table not allowed: ${t}` };
    }
  }
  const safe = /\blimit\b/i.test(s) ? s : `${s} LIMIT 200`;
  return { ok: true, safe };
}

export async function askMoney(question: string, model?: string) {
  // 1. NL -> SQL
  const sqlReply = await chat(
    [
      { role: "system", content: SQL_SYSTEM },
      { role: "user", content: question },
    ],
    // Generous budget: reasoning models (gemini-flash, gpt-5 mini, etc.) spend
    // most tokens thinking before emitting the JSON. 400 truncated them mid-SQL.
    { maxTokens: 1500, model }
  );
  const gen = extractJson<{ sql: string; note?: string }>(sqlReply);
  if (!gen?.sql) {
    // Reasoning models (gemini-flash, o-series) may spend the whole budget
    // thinking and truncate before the JSON. Surface a useful hint.
    const hint = sqlReply.trim().length === 0
      ? "the model returned nothing (it may have hit its token limit while reasoning — try a non-reasoning model)"
      : "could not parse a query from the model's reply";
    return { error: hint, raw: sqlReply.slice(0, 200) };
  }

  // 2. Validate
  const v = validateSql(gen.sql);
  if (!v.ok) return { error: `unsafe query: ${v.reason}`, sql: gen.sql };

  // 3. Execute on a fresh read-only handle
  let rows: unknown[];
  try {
    rows = db().prepare(v.safe!).all();
  } catch (e: unknown) {
    return { error: `query failed: ${e instanceof Error ? e.message : String(e)}`, sql: v.safe };
  }

  // 4. Narrate (also generous, so reasoning models don't truncate the answer)
  const answer = await chat(
    [
      { role: "system", content: ANSWER_SYSTEM },
      { role: "user", content: `Question: ${question}\nRows: ${JSON.stringify(rows).slice(0, 4000)}` },
    ],
    { maxTokens: 800, model }
  );

  return { answer: answer.trim(), sql: v.safe, note: gen.note, rowCount: rows.length };
}

// ---------------------------------------------------------------------------
// ACTION LAYER: let chat propose edits (never run free-form writes).
// Flow: classify intent -> if edit, the LLM writes a SELECT to FIND the target
// txns + proposes whitelisted field changes -> we return a proposal -> the user
// confirms in the UI -> applyEdit() runs a parameterized UPDATE on those ids.
// The LLM never emits an UPDATE; it can only pick rows (via validated SELECT)
// and choose new values from a fixed whitelist. That keeps the write path safe.
// ---------------------------------------------------------------------------

import { CATEGORIES } from "./taxonomy";

const EDITABLE_FIELDS = ["category", "entity", "merchant", "reviewed"] as const;
type EditableField = (typeof EDITABLE_FIELDS)[number];

const INTENT_SYSTEM = `Classify the user's message about their finances into one intent.
Output ONLY JSON: {"intent": "ask" | "edit"}.
- "ask" = a question that reads data ("how much…", "what was…", "show me…").
- "edit" = a request to CHANGE a transaction's category, entity (personal vs
  business / shared), or merchant name ("mark the 5000 as a transfer", "that was
  internal", "recategorize Pennymac as Mortgage", "set X to personal"). No prose.`;

const FIND_SYSTEM = `The user wants to EDIT one or more transactions. Produce ONLY JSON:
{"sql":"<SELECT that finds the target transactions>","changes":{<field>:<value>,...},"summary":"<one line>"}
Schema:${SCHEMA}
Rules:
- The SELECT must return at least id, date, name, merchant, amount, category, entity.
  Make it specific. IMPORTANT: merchant is OFTEN NULL — the payee/description is in
  the 'name' column. Always search BOTH: (lower(name) LIKE '%x%' OR lower(merchant) LIKE '%x%').
  When the user names a dollar amount, match on amount (amount is POSITIVE for money
  going out, e.g. a $5,000 payment is amount = 5000). LIMIT 25.
- "changes" may ONLY use these fields: category, entity, merchant, reviewed.
  - category must be one of: ${CATEGORIES.join(", ")}.
  - entity is 'personal' or 'business' (business = shared/business). A transfer to a
    partner's shared account = category 'Transfer:Internal'.
  - reviewed is true or false.
- SELECT only in "sql" (no UPDATE/INSERT/etc). Single statement, no semicolons.
- summary: plain-English of the change, e.g. "Mark the $5,000 transaction as Transfer:Internal".`;

export async function classifyIntent(message: string, model?: string): Promise<"ask" | "edit"> {
  try {
    const r = await chat(
      [{ role: "system", content: INTENT_SYSTEM }, { role: "user", content: message }],
      { maxTokens: 200, model }
    );
    const j = extractJson<{ intent: string }>(r);
    return j?.intent === "edit" ? "edit" : "ask";
  } catch {
    return "ask"; // default to the safe (read-only) path
  }
}

export interface EditProposal {
  kind: "proposal";
  summary: string;
  changes: Partial<Record<EditableField, string | boolean>>;
  ids: string[];
  preview: { id: string; date: string; label: string; amount: number; category: string | null; entity: string }[];
  sql: string;
}

// Builds an edit proposal WITHOUT writing anything. Returns rows it would change.
export async function proposeEdit(message: string, model?: string): Promise<EditProposal | { error: string }> {
  const reply = await chat(
    [{ role: "system", content: FIND_SYSTEM }, { role: "user", content: message }],
    { maxTokens: 1500, model }
  );
  const gen = extractJson<{ sql: string; changes: Record<string, unknown>; summary?: string }>(reply);
  if (!gen?.sql || !gen.changes) return { error: "couldn't work out which transaction to change — try naming the amount or merchant" };

  // Validate the finder SELECT with the same gate as reads.
  const v = validateSql(gen.sql);
  if (!v.ok) return { error: `unsafe finder query: ${v.reason}` };

  // Sanitize proposed changes against the whitelist.
  const changes: Partial<Record<EditableField, string | boolean>> = {};
  for (const [k, val] of Object.entries(gen.changes)) {
    if (!EDITABLE_FIELDS.includes(k as EditableField)) continue;
    if (k === "category") {
      if (typeof val === "string" && (CATEGORIES as readonly string[]).includes(val)) changes.category = val;
    } else if (k === "entity") {
      if (val === "personal" || val === "business") changes.entity = val;
    } else if (k === "reviewed") {
      changes.reviewed = val === true || val === "true";
    } else if (k === "merchant") {
      if (typeof val === "string" && val.trim()) changes.merchant = val.trim();
    }
  }
  if (Object.keys(changes).length === 0) return { error: "no valid change to apply (allowed: category, entity, merchant, reviewed)" };

  let rows: { id: string; date: string; name: string; merchant: string | null; amount: number; category: string | null; entity: string }[];
  try {
    rows = db().prepare(v.safe!).all() as unknown as typeof rows;
  } catch (e: unknown) {
    return { error: `finder failed: ${e instanceof Error ? e.message : String(e)}` };
  }
  if (rows.length === 0) return { error: "no matching transaction found" };

  return {
    kind: "proposal",
    summary: gen.summary ?? "Apply the change",
    changes,
    ids: rows.map((r) => r.id),
    preview: rows.map((r) => ({
      id: r.id, date: r.date, label: r.merchant ?? r.name, amount: r.amount,
      category: r.category, entity: r.entity,
    })),
    sql: v.safe!,
  };
}

// --- Batch "fix Other" flow: suggest a real category for every uncategorized /
// Other transaction, returned as per-row suggestions the user can tweak + apply. ---
export interface BatchItem {
  id: string; date: string; label: string; amount: number;
  current: string | null; suggested: string;
}

export async function proposeBatchCategories(model?: string): Promise<{ kind: "batch"; items: BatchItem[] } | { error: string }> {
  const d = db();
  const rows = d.prepare(
    `SELECT id, name, merchant, amount, category
     FROM transactions
     WHERE category IS NULL OR category = 'Other'
     ORDER BY ABS(amount) DESC LIMIT 40`
  ).all() as unknown as { id: string; name: string; merchant: string | null; amount: number; category: string | null }[];

  if (rows.length === 0) return { error: "nothing in 'Other' or uncategorized — you're all set 🎉" };

  const payload = rows.map((r) => ({ id: r.id, name: r.name, merchant: r.merchant, amount: r.amount }));
  const sys = `You categorize personal bank transactions. For EACH input, pick the single best
category from: ${CATEGORIES.join(", ")}. Avoid 'Other' unless truly nothing fits.
Output ONLY a JSON array: [{"id":"<id>","category":"<one category>"}]. No prose.`;
  const reply = await chat(
    [{ role: "system", content: sys }, { role: "user", content: JSON.stringify(payload) }],
    { maxTokens: 2000, model }
  );
  const parsed = extractJson<{ id: string; category: string }[]>(reply);
  const byId = new Map((Array.isArray(parsed) ? parsed : []).map((p) => [p.id, p.category]));

  const items: BatchItem[] = rows.map((r) => {
    const s = byId.get(r.id);
    const suggested = s && (CATEGORIES as readonly string[]).includes(s) ? s : "Other";
    return {
      id: r.id, date: "", label: r.merchant ?? r.name, amount: r.amount,
      current: r.category, suggested,
    };
  });
  return { kind: "batch", items };
}

// Applies per-row category choices (different category per id) from the batch flow.
export function applyBatch(items: { id: string; category: string }[]): { updated: number } {
  const d = db();
  const stmt = d.prepare(`UPDATE transactions SET category=?, category_source='manual', confidence=1.0, reviewed=1 WHERE id=?`);
  let updated = 0;
  for (const it of items) {
    if (!it.id || !(CATEGORIES as readonly string[]).includes(it.category)) continue;
    const r = stmt.run(it.category, it.id);
    updated += Number(r.changes ?? 0);
  }
  return { updated };
}

// Applies a confirmed proposal: parameterized UPDATE on the exact ids only.
// A manual edit pins category_source='manual' so the LLM categorizer won't undo it.
export function applyEdit(ids: string[], changes: Partial<Record<EditableField, string | boolean>>): { updated: number } {
  if (!ids.length || !Object.keys(changes).length) return { updated: 0 };
  const sets: string[] = [];
  const args: (string | number)[] = [];
  if (changes.category !== undefined) { sets.push("category=?", "category_source='manual'", "confidence=1.0"); args.push(String(changes.category)); }
  if (changes.entity !== undefined) { sets.push("entity=?"); args.push(String(changes.entity)); }
  if (changes.merchant !== undefined) { sets.push("merchant=?"); args.push(String(changes.merchant)); }
  if (changes.reviewed !== undefined) { sets.push("reviewed=?"); args.push(changes.reviewed ? 1 : 0); }
  if (!sets.length) return { updated: 0 };

  const d = db();
  const placeholders = ids.map(() => "?").join(",");
  const res = d.prepare(`UPDATE transactions SET ${sets.join(", ")} WHERE id IN (${placeholders})`)
    .run(...(args as never[]), ...(ids as never[]));
  return { updated: Number(res.changes ?? 0) };
}
